### ISSUE TITLE
Missing NPC/monster buff tooltip

### ISSUE THREAD

**Issue by ghost** [pauljarrett61/Projects#1]
Certain buffs don't have a tooltip. Do you think it's caused by this mod? My friend is using vanilla SWG (on Legends) and he can see them just fine.
It's the buffs that appear on the first line above the others, from boss/elite mobs.
Great mod I've been using it for months!

**Comment by pauljarrett61** [comment]
I'll have a look, were you in a heroic, I've not done any so not seen it

**Comment by ghost** [comment]
I was doing world bosses. So it was probably a buff like Gorax's that appears alone one the first row (above any others even if there's an entire line).

**Comment by pauljarrett61** [comment]
I've checked the vanilla file against the ilm one that i used and they are the same except for the sizes that i modified, the tooltips are active for both states and debuff bars, i'll have to replicate it to see the missing tooltip and try to see whats going on. Thanks for the heads up.

**Comment by ghost** [comment]
I found the problem. The first (your own) hud bar has a few transparent pixels. If there's even 1px of overlap with the second one the first buff icon will not work. If there's more than that then the entire line will not work.
Sorry for the noise.
